language: c
branches:
  except:
  - debian
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
install: 
  - sh .travis/before_install
group: travis_latest
script: ./autogen.sh && ./configure --enable-syslog && make NBD_TEST_SILENT=1 distcheck
