language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
install: 
  - sh .travis/before_install
group: travis_latest
script: ./autogen.sh && ./configure --enable-syslog && make && make NBD_TEST_SILENT=1 check
